commercetools/nimbus

- packages/nimbus/src/components/alert/alert.slots.tsx
While migrating, I encountered `"<div/p> cannot be descendants of <p>"` errors. So, best to use a `div` as the container for possibly highly styled children. This should cause no regression.
In the end, you were right @misama-ct 😆 🚀
> chore(nimbus): change `Alert` roots

- .prettierignore
This pull request includes a small update to the `.prettierignore` file. The change adds a rule to ignore all `.mdx` files during Prettier formatting.
See [this slack thread](https://commercetools.slack.com/archives/C045CH797B2/p1745326581078499) for context/details
> Do not run `prettier` in `mdx` files

- packages/nimbus/src/components/checkbox/checkbox.stories.tsx
- packages/nimbus/src/components/checkbox/checkbox.tsx
- pnpm-lock.yaml
This pull request introduces several updates and improvements to the `Checkbox` component in `packages/nimbus` and updates dependencies in the `pnpm-lock.yaml` file. The key changes include adding support for style props in the `Checkbox` component, introducing a new story to test these props, and upgrading various dependencies to newer versions.
* **Support for Style Props in Checkbox**: Added the `extractStyleProps` utility to split style-related props from the rest, enabling the `Checkbox` component to support custom styles such as margins. Updated the `Checkbox` render method to include these style props. (`checkbox.tsx`, [[1]](diffhunk://#diff-fc89418f7e88282233133689f06e54fdfa17963c6cbb1ab005e5f532c2fee745R44-R47) [[2]](diffhunk://#diff-fc89418f7e88282233133689f06e54fdfa17963c6cbb1ab …
> FCT-Make-Stephanie-Happy | Checkbox - make sure style props are passed to root component

- apps/docs/src/atoms/nimbus-version.ts
- apps/docs/src/components/navigation/app-nav-bar/components/app-nav-bar-brand.tsx
This version-badge will be useful once we set up the deployment of the docs. It allows us to spot immediately if the deployed version is the expected version.
(Trying out cursor, since we have only one week.)
> feat(nimbus): add nimbus package version to docs navbar

- packages/nimbus/package.json
I just merged the [PR](https://github.com/commercetools/nimbus/pull/77) with the change that displays the current nimbus version in the docs-app. Unfortunately though, the latest PR regarding the package-publishing changed the way exports work, making it necessary to explicitly declare the `package.json` file as export.
> fix(nimbus): include package.json as export in exports-object

- packages/nimbus/src/components/alert/alert.tsx
- packages/nimbus/src/components/alert/components/alert.actions.tsx
- packages/nimbus/src/components/alert/components/alert.description.tsx
- packages/nimbus/src/components/alert/components/alert.dismiss-button.tsx
- packages/nimbus/src/components/alert/components/alert.root.tsx
- packages/nimbus/src/components/alert/components/alert.title.tsx
- packages/nimbus/src/components/card/card.tsx
- packages/nimbus/src/components/card/components/card.content.tsx
- packages/nimbus/src/components/card/components/card.header.tsx
- packages/nimbus/src/components/card/components/card.root.tsx
> [!NOTE]
> There is no API change, this is purely cosmetic
This pull request refactors the `Alert` and `Card` components in the `nimbus` package to adopt named exports instead of default exports. This change improves consistency and simplifies imports across the codebase. The refactor also includes updates to the corresponding component files to align with this new export style.
* Updated `Alert` subcomponents (`AlertTitle`, `AlertDescription`, `AlertActions`, `AlertDismissButton`, and `AlertRoot`) to use named exports instead of default exports. This involved modifying the export statements and updating import statements in `alert.tsx`. [[1]](diffhunk://#diff-fdc9cddea72402630596664133ed4f1edd85554437530797f0e1a27fc93e5c8cL1-R5) …
> chore(nimbus): get rid of remaining default exports

- packages/nimbus/.gitignore
The output folder for the static-build of storybook was not in the .gitignore file yet.
> chore(gitignore): add Storybook log and static files to .gitignore

- .github/dependabot.yml
This PR is an attempt to provide a bit of context to dependabot, as it currently does not seem to grasp how dependencies are managed (monorepo, pnpm, workspaces, catalogs) and thus provides [unmergeable PR's](https://github.com/commercetools/nimbus/pull/92) (a change in the lock-file is not enough, the exact versions are specified in the `pnpm-workspace.yaml` file).
> chore(dependabot): add configuration for dependabot updates

- packages/nimbus/package.json
- packages/nimbus/src/components/accordion/accordion-context.tsx
- packages/nimbus/src/utils/fixedForwardRef.ts
- packages/nimbus/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
This pull request updates the `@commercetools/nimbus` package to improve compatibility, modernize dependencies, and simplify the build configuration. Key changes include updating React and related dependencies, switching the build output format from UMD to CommonJS, and refining type definitions for improved type safety.
* Updated React and React DOM to version `^19.0.0` in `pnpm-workspace.yaml` for compatibility with the latest React features.
* Updated `react-aria`, `react-aria-components`, and `react-stately` to newer versions in `pnpm-workspace.yaml` for enhanced functionality and bug fixes.
* Changed the build output format from UMD to CommonJS in `vite.config.ts` and updated the `main` field in `package.json` to reflect this change. This simplifies the build process and aligns with …
> FCT-1515 | use react 19, implement cjs build for environments that require it (eg `jest`)

- packages/nimbus/src/components/image/image.mdx
- packages/nimbus/src/components/image/image.tsx
- packages/nimbus/src/components/image/index.ts
- packages/nimbus/src/components/index.ts
I proxied the Image component from Chakra-UI and added an mdx-document explaining the usage. We didn't add stories yet for the other primitives we proxied (Box, Flex, etc.), so I didn't add any for Image either.
No need to run the branch locally anymore, [here is the vercel link for the docs-page](https://nimbus-documentation-git-fct-1495-design-s-7f5813-commercetools.vercel.app/components/media/image)
---
> FCT-1495: Nimbus - Image component

- .github/workflows/build-and-test.yml
This pull request updates the GitHub Actions workflow to focus on building and testing Nimbus components instead of deploying to GitHub Pages. The changes streamline the workflow by removing unnecessary steps and enhancing the build process for components.
* Renamed `.github/workflows/gh-pages.yml` to `.github/workflows/build-and-test.yml` and updated the workflow name to "Build and Test Nimbus Components." Added a trigger for `pull_request` events.
* Modified the build step to use `pnpm build:tokens && pnpm run build:packages` instead of `pnpm build`, excluding documentation builds since they don't have tests.
* Commented out the linting step due to its long runtime and limited utility in the current workflow. Added a note to revisit this for typechecking in the future.
* Removed the …
> feat(tests): set up workflow to test in ci for pr's

- packages/nimbus/src/components/icon/icon.mdx
- packages/nimbus/src/components/icon/icon.recipe.tsx
- packages/nimbus/src/components/icon/icon.slots.tsx
- packages/nimbus/src/components/icon/icon.stories.tsx
- packages/nimbus/src/components/icon/icon.tsx
- packages/nimbus/src/components/icon/icon.types.ts
- packages/nimbus/src/components/icon/index.ts
- packages/nimbus/src/components/index.ts
Icon component. Added to allow coloring and sizing of icons in an orderly fashion.
- [Documentation](https://nimbus-documentation-git-fct-1517-nimbus-c-94a51a-commercetools.vercel.app/components/media/icon)
- [Stories](https://nimbus-storybook-git-fct-1517-nimbus-compo-b8ca16-commercetools.vercel.app/?path=/docs/components-icon--docs)
> FCT-1517: Nimbus - Icon component

- packages/nimbus/src/components/form-field/form-field.stories.tsx
- packages/nimbus/src/components/text-input/text-input.slots.tsx
- packages/nimbus/src/components/text-input/text-input.stories.tsx
- packages/nimbus/src/components/text-input/text-input.tsx
- packages/nimbus/src/components/text-input/text-input.types.ts
After ditching the idea of changing the`onChange` handler back to propagating a regular `ChangeEvent` instead of the value itself, the only functional change is ditching react-arias `TextField` component in favor of the `useTextField` hook.
I did this, cause the `TextField` component was adding an additional, unnecessary div around the input which caused some issues when attempting to apply additional style-props to the `TextInput`.
The component is now wiring only the needed props (`inputProps`) from the hook to `Input`.
> FCT-1469: Nimbus - TextInput - Resolve layouting issues with style-props

- packages/nimbus/src/components/icon-button/icon-button.tsx
fix(icon button): use merged props from `useContextProps`, but do not use resulting ref
Fixes an issue where the `IconButton` component was causing the popover to display in an unexpected position when the `clear` button is present in the `Select` component
Issue is fixed by not passing the `ref` generated by `useContextProps` to the `Button` component, and instead allowing the `useButton` hook to generate the appropriate `ref` in the underlying `Button` component.  This can be verified by looking at the [formfield storybook for this branch](https://nimbus-storybook-git-bw-fix-icon-button-issue-commercetools.vercel.app/?path=/story/components-formfield--using-a-select-input).
> fix(IconButton): fix issue where iconButton was causing unexpected behavior in Select component

- packages/nimbus/src/components/link/link.mdx
- packages/nimbus/src/components/link/link.stories.tsx
- packages/nimbus/src/components/link/link.types.tsx
- packages/nimbus/src/components/toggle-button-group/toggle-button-group.stories.tsx
**Link**
- `onClick` was not properly typed, causing a ts error during build
- the `FontColors` story's choice of background-color caused an unnecessary a11y complaint
**ToggleButtonGroup**
- Buttons in the `Tones` story did not have an `aria-label`, causing a11y tests to fail
> chore(tests+ts): Fix misc issues

- packages/nimbus/src/components/index.ts
- packages/nimbus/src/components/password-input/index.ts
- packages/nimbus/src/components/password-input/password-input.mdx
- packages/nimbus/src/components/password-input/password-input.stories.tsx
- packages/nimbus/src/components/password-input/password-input.tsx
- packages/nimbus/src/components/password-input/password-input.types.ts
This PR introduces a new PasswordInput component to the Nimbus design system, providing a secure and user-friendly way for users to enter passwords with the option to toggle visibility.
- [Storybook Stories](https://nimbus-storybook-git-fct-1520-nimbus-compo-8df53a-commercetools.vercel.app/?path=/docs/components-passwordinput--docs)
- [Documentation](https://nimbus-documentation-git-fct-1520-nimbus-c-a7586e-commercetools.vercel.app/components/inputs/passwordinput) (no usage guidelines yet)
- **Password Visibility Toggle:**
Users can easily switch between masked and visible password input using an integrated toggle button.
- **Accessibility:**
- Fully keyboard-accessible, including toggling visibility with Enter/Space.
- Proper ARIA labels for improved screen reader support.
- Toggle …
> FCT-1520: Nimbus - Add PasswordInput Component

- packages/nimbus/src/components/card/card.tsx
Prepend exports with an underscore to indicate that this exports are only used for the typescript type parser.
> refactor(card): update exports to include prefixed component names

- packages/nimbus/src/components/form-field/components/form-field.context.tsx
- packages/nimbus/src/components/form-field/components/form-field.description.tsx
- packages/nimbus/src/components/form-field/components/form-field.error.tsx
- packages/nimbus/src/components/form-field/components/form-field.info-box.tsx
- packages/nimbus/src/components/form-field/components/form-field.input.tsx
- packages/nimbus/src/components/form-field/components/form-field.label.tsx
- packages/nimbus/src/components/form-field/components/form-field.root.tsx
- packages/nimbus/src/components/form-field/form-field.tsx
The `FormFieldContext` component is not exported anymore, the PropsTable for `FormField` now shows all sub-components props.
- Moved `FormFieldContext` and its types to a new file so that it's not exported by default anymore
- Updated component imports to reference the new context file.
- Added the necessary "types-exports" to the main component file
> refactor(form-field): get the props-table to work

- packages/nimbus/src/components/toggle-button-group/toggle-button-group.mdx
- packages/nimbus/src/components/toggle-button-group/toggle-button-group.tsx
- Changed the title in the documentation from "Toggle Button Group" to "ToggleButtonGroup" for consistency.
- Updated exports in the TypeScript file to include prefixed component names for better clarity.
[Ticket](https://commercetools.atlassian.net/browse/FCT-1551)
> refactor(toggle-button-group): update component title and adjust exports

- packages/nimbus/src/components/form-field/form-field.stories.tsx
- pnpm-lock.yaml
- pnpm-workspace.yaml
In an attempt to get rid of random a11y issues popping up in the test-runner, I tried updating to the latest available v8 version. Not sure it'll help, but the closer we're to the v9 version the easier will be the transition to that new major version.
> chore(storybook): update to latest v8 version

- packages/nimbus/src/theme/global-css.ts
The customers team [pointed out](https://commercetools.slack.com/archives/C08GSD5FAV6/p1749643760916179) that nimbus seemed to be causing an issue with `svg` elements not aligning correctly in non-nimbus components in the MC.  
Upon further investigation, [chakra's ](https://chakra-ui.com/docs/theming/overview#preflight)`preflight` css reset [does indeed](https://github.com/chakra-ui/chakra-ui/blob/39b814f597ba11fda6b5b0e727b303c145c52a79/packages/react/src/styled-system/preflight.ts#L45) override `svg` `display` and `verticalAlign` properties.
This fix overrides the `@reset` layer by setting `display: "initial"` and `verticalAlign: "initial"` for `img, svg, video, canvas, audio, iframe, embed, object` elements in the `globalCss` theme.
> feat(reset): override styling of svgs and other media elements in chakra theme's @reset layer

- packages/nimbus/src/components/combobox/combobox.stories.tsx
- packages/nimbus/src/components/combobox/components/combobox.multi-select-root.tsx
- packages/nimbus/src/components/combobox/components/combobox.single-select-input.tsx
- packages/nimbus/src/components/combobox/components/combobox.single-select-root.tsx
Updates the single-select combobox to better handle user input in cases where the combobox has a previous value set.
When there is a `selectedKey` set on the single select, the user can more easily update it by typing in the input:
- when the input gains focus, the cursor moves to the beginning of the input
- if the user enters text, the previous value is cleared and that text is displayed
- if the user selects an option, the new option is the displayed value
- if the user does not select an option, the selected value replaces the user's input when the combobox is blurred.
Current `main`:
This branch:
Also makes focus management when toggling the dropdown more robust, and uses `closePopover` method consistently in tests.
> CRAFT-1600 | Single Select Combobox UX

- package.json
- packages/nimbus/package.json
- packages/nimbus/vite.config.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Adds vite-bundle-analyzer vite plugin and bundles:analyze script to enable visual analysis of bundle size.
To use, run `pnpm bundles:analyze` from the `packages/nimbus` directory.
> Add bundle analysis tool/script

- packages/nimbus/src/components/combobox/combobox.recipe.tsx
- packages/nimbus/src/components/select/select.recipe.tsx
- packages/nimbus/src/components/tag-group/tag-group.recipe.tsx
This pull request updates the handling of `data-disabled`, `data-selected`, and `aria-selected` attributes in component recipes for `Tag` and `Select`.
Attribute handling updates:
* [`packages/nimbus/src/components/select/select.recipe.tsx`](diffhunk://#diff-31e6b790167ce54b8a21f8e6acbc6bea4c203887c19940743934640b618e224eL33-R33): Changed `&[data-disabled]` to `&[data-disabled="true"]` for more explicit attribute matching.
* [`packages/nimbus/src/components/tag-group/tag-group.recipe.tsx`](diffhunk://#diff-130e007c197b6a006ec1595c418ad56bcc54cefaef52fedfb070ab593acb4ff1L32-R41): Updated `&[data-disabled] &`, `&[data-selected]`, and `&[aria-selected]` to use explicit attribute-value pairs (`&[data-disabled="true"] &`, `&[data-selected="true"]`, and `&[aria-selected="true"]`). This ensures …
> fix(select, tag): update disabled recipe syntax

- .changeset/chatty-experts-jump.md
- .changeset/config.json
- .changeset/modern-flies-taste.md
- .github/workflows/release.yml
Seeing if this works. Previous PR had errors authenticating, so now we're using the token strategy used in every other repo
> chore(nimbus): fix CI auth

- packages/nimbus/src/components/rich-text-input/components/rich-text-toolbar.tsx
This pull request introduces an improvement to the `RichTextToolbar` component by ensuring the editor is refocused when the formatting menu is closed. This should enhance the user experience by allowing users to continue typing immediately after interacting with the formatting options.
**Rich Text Toolbar usability improvements:**
* Added an `onClose` handler to the formatting menu in `RichTextToolbar` that refocuses the editor after the menu is closed, using `focusEditor` with a short delay to ensure proper timing.
* Imported the `focusEditor` utility function from `rich-text-utils` to support the new focus behavior.
> Rich Text Editor - PoC for moving focus from toolbar to editor

- .changeset/gold-planes-shout.md
- packages/nimbus/package.json
- packages/nimbus/src/components/data-table/data-table.recipe.tsx
- packages/nimbus/src/components/data-table/data-table.slots.tsx
- packages/nimbus/src/components/data-table/data-table.types.ts
- packages/nimbus/src/theme/slot-recipes/index.ts
- packages/nimbus/vite.config.ts
This pull request improves the external configuration for Chakra UI in the build setup. It also registers the DataTable slot recipe in the theme system, and refactors the DataTable component to consistently use the `dataTableSlotRecipe` naming convention, and updates related type interfaces and imports throughout the codebase.
**Build Configuration**
* Updated the Vite configuration to use a regular expression for Chakra UI externals, improving compatibility with different import patterns.
**Theme System Integration**
* Registered `dataTableSlotRecipe` in the slot recipes theme system by importing and adding it to the `slotRecipes` object in `slot-recipes/index.ts`. [[1]](diffhunk://#diff-a0c0b51c3a05b3e71eb9faa9d95dd314e0fbd04d50aff7e44ab46771ffc14365R17) …
> Nimbus Tooling - Update handling of `@chakra-ui/react` external dependency to use a regular expression so that chakra is not bundled with nimbus

- packages/nimbus/src/components/money-input/money-input.i18n.ts
- packages/nimbus/src/components/money-input/money-input.recipe.tsx
- packages/nimbus/src/components/money-input/money-input.slots.tsx
- packages/nimbus/src/components/money-input/money-input.stories.tsx
- packages/nimbus/src/components/money-input/money-input.tsx
- packages/nimbus/src/components/money-input/money-input.types.ts
- packages/nimbus/src/components/money-input/utils/static-methods.ts
- packages/nimbus/src/components/number-input/number-input.slots.tsx
- packages/nimbus/src/components/number-input/number-input.tsx
This pull request refactors the `MoneyInput` component and its stories to improve accessibility, consistency, and maintainability. The changes focus on using more semantic ARIA roles and labels, aligning test queries with accessibility best practices, and cleaning up component internals. The most important changes are outlined below.
**Accessibility and ARIA improvements:**
* Replaced test IDs and placeholder-based queries in Storybook stories with ARIA roles and accessible names, ensuring all test interactions use `getByRole` or `getByLabelText` for elements like currency select, amount input, and high precision badges. This aligns the component and its tests with accessibility standards. [[1]](diffhunk://#diff-f00f2285d317b126da13211c6b022d4d71f88d0ba3d3fed804cd7cdc9907869fL101-R124) …
> Craft 1742 | a11y updates

- packages/nimbus/src/components/data-table/components/data-table.row.tsx
- packages/nimbus/src/components/data-table/data-table.recipe.tsx
- packages/nimbus/src/components/data-table/data-table.stories.tsx
- The selection checkbox buttons of the data table, along with the collapsible button and the pin row buttons currently scroll along with the data table. These three columns should be fixed while scrolling horizontally. they should always remain in their position while the rest of the table columns scroll horizontally. 
- Make the pin rows feature of the Data table sticky and always visible without it scrolling out of view.
- Fix pin hover effect that somehow stopped worked.
- Use the opportunity to clean up unused leftover code. 
How to test:
- Go to the all features story 
- Enable `Show all columns"
- Enable Text truncation for a simplified ui. 
- Interact with the select, expand and pin buttons, and also scroll the table horizontally. 
**Result**: these 3 buttons should always stay …
> Nimbus - Data table - fix interactive columns against horizontal scroll

- .github/workflows/build-and-test.yml
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR updates workspace dependencies to their latest minor and patch versions while maintaining compatibility.
**🔧 TOOLING GROUP** (9 packages updated):
- `eslint`: 9.35.0 → 9.36.0
- `storybook`: 9.1.5 → 9.1.8 
- `eslint-plugin-storybook`: 9.1.5 → 9.1.8
- `@storybook/addon-*`: 9.1.5 → 9.1.8 (4 packages)
- `@storybook/react-vite`: 9.1.5 → 9.1.8
- `vite`: 7.1.5 → 7.1.7
- `rollup`: 4.50.1 → 4.52.2
- `typescript-eslint`: 8.42.0 → 8.44.1
- `playwright`: 1.55.0 → 1.55.1
**⚛️ REACT GROUP** (4 packages updated):
- `@chakra-ui/cli`: 3.26.0 → 3.27.0
- `@chakra-ui/react`: 3.26.0 → 3.27.0
- `react-aria`: 3.43.1 → 3.43.2
- `react-aria-components`: 1.12.1 → 1.12.2
- Updated catalog dependencies in pnpm-workspace.yaml
- Regenerated pnpm-lock.yaml with latest versions
- All builds and tests pass …
> chore(deps): update workspace dependencies to latest minor/patch versions

- .changeset/config.json
- package.json
- packages/i18n/README.md
- packages/i18n/package.json
**1.)** This PR introduces a new data-only package for Nimbus i18n translations, specifically designed for `mc-appkit` integration.
Taking a simpler approach than uikit... may/ may not work.
TL;DR This is to enable Nimbus components to display localized text in all MC applications.
Why package like this?
- Contains zero code - only translation JSON files in multiple formats (raw + compiled AST)
- No need for entrypoints, dependencies, preconstruct, etc
- Direct consumption by appkit, merge with other sources in `packages/i18n/src/load-i18n.ts`
- Tree-shakeable by nature
**2.)** Made a few changes to the i18n scripts
**3.)** Note that the README isn't really a part of this, but only a draft. Not sure if this is better kept here, or w/in the Nimbus package itself. tbd.
> CRAFT-1759 - Package Nimbus i18n for App-Kit Integration
